dist: focal

language: python

python:
  - "3.8"

install:
  - pip install docker pytest

services:
  - docker

script:
  - bash scripts/test.sh

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master